services:
  postgres:
    image: postgres:15
    container_name: jobfair_microservice_postgres_dev
    environment:
      POSTGRES_DB: jobfair
      POSTGRES_USER: jobfair_user
      POSTGRES_PASSWORD: jobfair_pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - jobfair_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobfair_user -d jobfair"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: jobfair_auth_dev
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://jobfair_user:jobfair_pass@postgres:5432/jobfair?sslmode=disable
      JWT_SECRET: your-super-secret-jwt-key-for-development
      PORT: 8080
      GIN_MODE: debug
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - jobfair_dev
    restart: unless-stopped
    
volumes:
  postgres_dev_data:

networks:
  jobfair_dev:
    driver: bridge