# Development environment with monitoring
services:
  # Database
  postgres:
    image: postgres:15
    container_name: jobfair_postgres_dev
    environment:
      POSTGRES_DB: jobfair
      POSTGRES_USER: jobfair_user
      POSTGRES_PASSWORD: jobfair_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - jobfair_network

  redis:
    image: redis:7-alpine
    container_name: jobfair_redis_dev
    ports:
      - "6379:6379"
    networks:
      - jobfair_network

  # Microservices (built from external repos)
  auth-service:
    build:
      context: ../../jobfair-auth-service      # Path to auth service repo
      dockerfile: Dockerfile
    container_name: jobfair_auth_dev
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://jobfair_user:jobfair_pass@postgres:5432/jobfair?sslmode=disable
      JWT_SECRET: dev-jwt-secret
      REDIS_URL: redis://redis:6379
      PORT: 8080
    depends_on:
      - postgres
      - redis
    networks:
      - jobfair_network
    restart: unless-stopped

  company-service:
    build:
      context: ../../jobfair-company-service   # Path to company service repo
      dockerfile: Dockerfile
    container_name: jobfair_company_dev
    ports:
      - "8081:8080"
    environment:
      DATABASE_URL: postgres://jobfair_user:jobfair_pass@postgres:5432/jobfair?sslmode=disable
      AUTH_SERVICE_URL: http://auth-service:8080
      PORT: 8080
    depends_on:
      - postgres
      - auth-service
    networks:
      - jobfair_network
    restart: unless-stopped

  api-gateway:
    build:
      context: ../../jobfair-api-gateway       # Path to gateway repo
      dockerfile: Dockerfile
    container_name: jobfair_gateway_dev
    ports:
      - "8000:8080"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8080
      COMPANY_SERVICE_URL: http://company-service:8080
      PORT: 8080
    depends_on:
      - auth-service
      - company-service
    networks:
      - jobfair_network
    restart: unless-stopped

  # Monitoring Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: jobfair_elasticsearch_dev
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_dev_data:/usr/share/elasticsearch/data
    networks:
      - jobfair_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: jobfair_kibana_dev
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - jobfair_network

  prometheus:
    image: prom/prometheus:latest
    container_name: jobfair_prometheus_dev
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_dev_data:/prometheus
    networks:
      - jobfair_network

  grafana:
    image: grafana/grafana:latest
    container_name: jobfair_grafana_dev
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=jobfair123
    volumes:
      - grafana_dev_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    networks:
      - jobfair_network

volumes:
  postgres_dev_data:
  elasticsearch_dev_data:
  prometheus_dev_data:
  grafana_dev_data:

networks:
  jobfair_network:
    driver: bridge